USE BIBLIOTECA;

GRANT INSERT ON Autor TO Juca;

DENY SELECT ON Editora TO Juca;

REVOKE SELECT ON EDITORA TO JUCA;

---
GO
USE EMPRESA;

GRANT INSERT ON FUNCIONARIO TO Andrisa;
GRANT ALTER TABLE TO Andrisa; --ERRADO

DENY DELETE TO Andrisa; --ERRADO