/* Lógico_1: */

CREATE TABLE LIVRO (
    ISBN VARCHAR(13) PRIMARY KEY,
    Titulo VARCHAR(255),
    Ano INT,
    FK_EDITORA_ID INT,
    FK_CATEGORIA_Codigo VARCHAR(5)
);

CREATE TABLE EDITORA (
    ID INT PRIMARY KEY IDENTITY,
    Nome VARCHAR(255),
    CNPJ VARCHAR(15) 
);

CREATE TABLE AUTOR (
    ID INT PRIMARY KEY IDENTITY,
    Nome VARCHAR(255),
    Nacionalidade VARCHAR(255)
);

CREATE TABLE CATEGORIA (
    Codigo VARCHAR(5) PRIMARY KEY,
    Descricao VARCHAR(255)
);

CREATE TABLE LIVRO_AUTOR (
    FK_LIVRO_ISBN VARCHAR(13),
    FK_AUTOR_ID INT
);
 
ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_2
    FOREIGN KEY (FK_EDITORA_ID)
    REFERENCES EDITORA (ID)
    ON DELETE CASCADE;
 
ALTER TABLE LIVRO ADD CONSTRAINT FK_LIVRO_3
    FOREIGN KEY (FK_CATEGORIA_Codigo)
    REFERENCES CATEGORIA (Codigo)
    ON DELETE CASCADE;
 
ALTER TABLE LIVRO_AUTOR ADD CONSTRAINT FK_LIVRO_AUTOR_1
    FOREIGN KEY (FK_LIVRO_ISBN)
    REFERENCES LIVRO (ISBN)
    ON DELETE SET NULL;
 
ALTER TABLE LIVRO_AUTOR ADD CONSTRAINT FK_LIVRO_AUTOR_2
    FOREIGN KEY (FK_AUTOR_ID)
    REFERENCES AUTOR (ID)
    ON DELETE SET NULL;
