--Consultas Aula

--DISTINCT
SELECT DISTINCT Salario
FROM FUNCIONARIO;

--WHERE
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Pnome = 'João';

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario <= 30000;

	--AND, OR and NOT
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Sexo = 'M' AND F.Salario >= 30000;

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Endereco LIKE '%São Paulo%' OR F.Endereco LIKE '%Curitiba%';

SELECT *
FROM FUNCIONARIO AS F
WHERE NOT F.Endereco LIKE '%São Paulo%';

--ORDER BY
SELECT *
FROM FUNCIONARIO AS F
ORDER BY F.Salario DESC;

--NULL
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Cpf_supervisor IS NULL;

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Cpf_supervisor IS NOT NULL;

--SELECT TOP
SELECT TOP 3 *
FROM FUNCIONARIO AS F
ORDER BY F.Salario DESC;

--FUNÇÕES
	--MIN()
SELECT MIN(F.Salario) 
FROM FUNCIONARIO AS F;

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario = (SELECT MIN(F.Salario) 
					FROM FUNCIONARIO AS F);

---DECLARE

DECLARE @Salario_Min DECIMAL(10,2);

/*SELECT @Salario_Min = (SELECT MIN(F.Salario) 
						FROM FUNCIONARIO AS F);
*/

SET @Salario_Min = (SELECT MIN(F.Salario) 
					FROM FUNCIONARIO AS F);

PRINT @Salario_Min;

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario = @Salario_Min;

	--MAX()
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario = (SELECT MAX(F.Salario) 
					FROM FUNCIONARIO AS F);

	--COUNT()
SELECT COUNT(F.Cpf)
FROM FUNCIONARIO AS F;

SELECT COUNT(*)
FROM DEPENDENTE;

SELECT
	(SELECT COUNT(*) FROM FUNCIONARIO AS N_Func),
	(SELECT COUNT(*) FROM DEPENDENTE AS N_Dep),
	(SELECT COUNT(*) FROM FUNCIONARIO AS N_Func) + (SELECT COUNT(*) FROM DEPENDENTE AS N_Dep) AS TOTAL;

DECLARE @N_Func INT;

DECLARE @N_Dep INT;

SET @N_Func = (SELECT COUNT(*) FROM FUNCIONARIO);
SET @N_Dep = (SELECT COUNT(*) FROM DEPENDENTE);

SELECT @N_Func + @N_Dep AS TOTAL;

	--AVG()
SELECT AVG(F.Salario)
FROM FUNCIONARIO AS F;

	--SUM()
SELECT SUM(F.Salario)
FROM FUNCIONARIO AS F;


--LIKE
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Datanasc LIKE '__72%';

SELECT *
FROM FUNCIONARIO AS F
WHERE YEAR(F.Datanasc) LIKE '__72%';

--IN
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario IN (25000, 30000);

SELECT *
FROM FUNCIONARIO AS F
	JOIN TRABALHA_EM AS T
	ON F.Cpf = T.Fcpf
WHERE F.Cpf = '33344555587';

SELECT *
FROM FUNCIONARIO AS F
	JOIN TRABALHA_EM AS T
	ON F.Cpf = T.Fcpf
WHERE T.Pnr IN (SELECT Pnr 
				FROM TRABALHA_EM 
				WHERE Fcpf = '33344555587')
				AND T.Horas IN (SELECT Horas
								FROM TRABALHA_EM
								WHERE Fcpf = '33344555587')
								AND NOT T.Fcpf = '33344555587';

DECLARE @Cpf_Fernando CHAR(11);

SET @Cpf_Fernando = (SELECT F.Cpf
					FROM FUNCIONARIO AS F
					WHERE F.Pnome = 'Fernando');

SELECT F.Pnome, T.*
FROM FUNCIONARIO AS F
	JOIN TRABALHA_EM AS T
	ON F.Cpf = T.Fcpf
WHERE T.Pnr IN (SELECT Pnr FROM TRABALHA_EM WHERE Fcpf = @Cpf_Fernando)
AND T.Horas IN (SELECT Horas FROM TRABALHA_EM WHERE Fcpf = @Cpf_Fernando)
AND NOT T.Fcpf = @Cpf_Fernando;

--ALIASES

SELECT *
FROM FUNCIONARIO AS F;
