
-- INNER JOIN
SELECT *
FROM FUNCIONARIO AS F
INNER JOIN TRABALHA_EM AS TE
ON TE.Fcpf = F.Cpf
INNER JOIN PROJETO AS P
ON TE.Pnr = P.Projnumero;

SELECT F.Pnome, F.Unome
FROM FUNCIONARIO AS F
INNER JOIN TRABALHA_EM AS TE
ON TE.Fcpf = F.Cpf
INNER JOIN PROJETO AS P
ON TE.Pnr = P.Projnumero
WHERE P.Projnome = 'ProdutoX';

SELECT P.Projnumero, P.Dnum, D.Cpf_gerente, F.Unome, F.Endereco, F.Datanasc
FROM PROJETO AS P
INNER JOIN DEPARTAMENTO AS D
ON P.Dnum = D.Dnumero
INNER JOIN FUNCIONARIO AS F
ON D.Cpf_gerente = F.Cpf
WHERE P.Projlocal = 'Mauá';

-- LEFT JOIN
SELECT F.Pnome AS 'F_Nome', F.Unome AS 'F_Sobrenome' ,S.Unome AS 'Supervisor'
FROM FUNCIONARIO AS F
LEFT JOIN FUNCIONARIO AS S -- Gerentes/Supervisores
ON F.Cpf_supervisor = S.Cpf;

SELECT D.Dnome, D.Dnumero
FROM DEPARTAMENTO AS D
LEFT JOIN FUNCIONARIO AS F
ON D.Dnumero = F.Dnr
WHERE F.Cpf IS NULL;

SELECT *
FROM FUNCIONARIO AS F
WHERE F.Dnr IS NULL;

-- RIGHT JOIN
SELECT D.Dnome, D.Dnumero
FROM FUNCIONARIO AS F
RIGHT JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
WHERE F.Cpf IS NULL;

-- CROSS JOIN/FULL JOIN
SELECT *
FROM FUNCIONARIO AS F
FULL JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero;

-- SELF JOIN
SELECT *
FROM FUNCIONARIO AS F
JOIN FUNCIONARIO AS S
ON F.Cpf_supervisor = S.Cpf;

-- UNION
SELECT F.Pnome, F.Sexo, F.Datanasc FROM FUNCIONARIO AS F
UNION
SELECT D.Nome_dependente, D.Sexo, D.Datanasc FROM DEPENDENTE AS D;

SELECT P.Projlocal FROM PROJETO AS P
UNION
SELECT LD.Dlocal FROM LOCALIZACAO_DEP AS LD;

	-- UNION ALL
	SELECT P.Projlocal FROM PROJETO AS P
	UNION ALL
	SELECT LD.Dlocal FROM LOCALIZACAO_DEP AS LD;

-- EXCEPT
SELECT F.Cpf FROM FUNCIONARIO AS F
EXCEPT
SELECT D.Cpf_gerente FROM DEPARTAMENTO AS D;

SELECT F.Pnome, F.Unome,F.Cpf
FROM FUNCIONARIO AS F
WHERE F.Cpf IN(
				SELECT F.Cpf
				FROM FUNCIONARIO AS F
				EXCEPT
				SELECT S.Cpf_supervisor
				FROM FUNCIONARIO AS S);

-- INTERSECT
SELECT F.Pnome FROM FUNCIONARIO AS F
INTERSECT
SELECT D.Nome_dependente FROM DEPENDENTE AS D;

-- GROUP BY
SELECT COUNT(F.Cpf) AS 'Qtd_Funcionarios', D.Dnome AS 'Departamento'
FROM FUNCIONARIO AS F
INNER JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

SELECT SUM(F.Salario) AS 'Soma_Salarios', D.Dnome AS 'Departamento'
FROM FUNCIONARIO AS F
INNER JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

SELECT AVG(TE.Horas) AS 'Media_Horas', P.Projnome
FROM PROJETO AS P
INNER JOIN TRABALHA_EM AS TE
ON P.Projnumero = TE.Pnr
GROUP BY P.Projnome;

SELECT COUNT(F.Sexo) AS 'Qtd_Funcionarios', F.Sexo
FROM FUNCIONARIO AS F
GROUP BY F.Sexo;

SELECT MAX(F.Salario) AS 'Maior_Salario', D.Dnome 
FROM FUNCIONARIO AS F
INNER JOIN DEPARTAMENTO AS D
ON F.Dnr = D.Dnumero
GROUP BY D.Dnome;

-- HAVING
SELECT COUNT(F.Cpf) AS 'Qtd_Funcionarios', D.Dnome
FROM DEPARTAMENTO AS D
INNER JOIN FUNCIONARIO AS F
ON D.Dnumero = F.Dnr
GROUP BY D.Dnome
HAVING COUNT(F.Cpf) > 3;

SELECT SUM(TE.Horas) AS 'Horas', P.Projnome
FROM TRABALHA_EM AS TE
INNER JOIN PROJETO AS P
ON TE.Pnr = P.Projnumero
GROUP BY P.Projnome
HAVING SUM(TE.Horas) >= 50;

-- EXISTS
SELECT *
FROM FUNCIONARIO AS F
WHERE EXISTS (
				SELECT 1
				FROM DEPARTAMENTO AS D

				WHERE F.Cpf = D.Cpf_gerente);

-- ALL (Todos)
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Salario > ALL (
						SELECT F.Salario
						FROM FUNCIONARIO AS F
						INNER JOIN DEPARTAMENTO AS D
						ON F.Dnr = D.Dnumero
						WHERE D.Dnumero = 4
						);

SELECT *
FROM PROJETO AS P
INNER JOIN TRABALHA_EM AS TE
ON P.Projnumero = TE.Pnr
WHERE TE.Horas > ALL (
						SELECT SUM(TE.Horas)
						FROM TRABALHA_EM AS TE
						INNER JOIN PROJETO AS P
						ON TE.Pnr = P.Projnumero
						WHERE P.Projlocal = 'Itu'
					);
